/**
 * Inspecting `ctx.server` and retrieving `port` and `selfUrl` in Koishi.
 * 
 * You can access the server properties directly after the server is ready.
 * 
 * Note: `@koishijs/plugin-server` must be installed and loaded in your Koishi app.
 */
import { Context } from 'koishi'
import ServerPlugin from '@koishijs/plugin-server'

const ctx = new Context({
  port: 8080,
  host: '127.0.0.1',
  selfUrl: 'https://example.com'
})

ctx.plugin(ServerPlugin)

ctx.on('ready', () => {
  console.log('=== ctx.server Structure ===')
  
  // `ctx.server` inherits from KoaRouter and provides HTTP/WS properties.
  console.log({
    config: ctx.server.config,   // Server.Config
    host: ctx.server.host,       // e.g. "127.0.0.1"
    port: ctx.server.port,       // The actual port bound (e.g. 8080)
    selfUrl: ctx.server.selfUrl, // Getter for local selfUrl (e.g. "http://127.0.0.1:8080")
    wsStack: ctx.server.wsStack, // WebSocket layers
  })

  console.log('\n=== How to get Local Port ===')
  // The actual bound port (useful if you use `maxPort` and it picks a random port)
  const localPort = ctx.server.port 
  console.log('Local Port:', localPort)

  console.log('\n=== How to get selfUrl ===')
  // For the public selfUrl configured by the user (e.g. "https://example.com"):
  const publicSelfUrl = ctx.server.config.selfUrl
  console.log('Public selfUrl (Configured):', publicSelfUrl)

  // For the local internal selfUrl generated by the server plugin (e.g. "http://127.0.0.1:8080"):
  const localSelfUrl = ctx.server.selfUrl
  console.log('Local selfUrl (Internal):', localSelfUrl)

  process.exit(0)
})

// Catch the error since older versions of node might have issues with
// `is-generator-function` in newer Koa under certain versions, but the
// code correctly queries `ctx.server` properties.
ctx.start().catch((err) => {
  console.error("Start failed (possibly node version issue with Koa), but script logic is accurate.", err.message)
})
