import { Context } from 'koishi'
import type {} from '@koishijs/plugin-server'

export const name = 'inspect-server'

// Ensure we have access to ctx.server
export const inject = ['server']

export function apply(ctx: Context) {
  ctx.on('ready', () => {
    ctx.logger.info('=== ctx.server Structure ===')
    
    // Log the basic structure of ctx.server
    ctx.logger.info({
      host: ctx.server.host,
      port: ctx.server.port,
      config: ctx.server.config,
      selfUrl: ctx.server.selfUrl, // local generated selfUrl
      wsStack: ctx.server.wsStack.length,
    })

    // How to get local port
    const localPort = ctx.server.port
    ctx.logger.info(`Local Port: ${localPort}`)

    // How to get selfUrl
    // 1. The public selfUrl configured by the user (recommended for external links)
    const publicSelfUrl = ctx.server.config?.selfUrl 
    
    // 2. The local selfUrl generated by the server
    const localSelfUrl = ctx.server.selfUrl 
    
    // Fallback logic
    const finalSelfUrl = publicSelfUrl || localSelfUrl
    
    ctx.logger.info(`Configured Public selfUrl: ${publicSelfUrl}`)
    ctx.logger.info(`Local Internal selfUrl: ${localSelfUrl}`)
    ctx.logger.info(`Final selfUrl to use: ${finalSelfUrl}`)
  })
}
